### ISSUE TITLE
Multiplayer End Game tracking

### ISSUE THREAD

**Issue by RosyMapleMoth** [RosyMapleMoth/Chain-Reaction-PoC#29]
add in proper multiplayer win con tracking

- [ ] Pause for everyone only one player is left.
- [ ] Show which player won
- [ ] Prompt players to either play again / change characters /  drop out

**Comment by RosyMapleMoth** [comment]
Rework for module rework system
